### ISSUE TITLE
Testing with an unreachable webhook

### ISSUE THREAD

**Issue by clemzarch** [mollie/orocommerce#22]
STR: on version 4.1.8, when trying to test the payment method on a local environment, checkout cannot be completed because the webhook URL (my local server) is unreachable from Mollie's point of view.
Would it be possible to bypass this check when in Test mode?

**Comment by logeecom** [comment]
Unfortunately no. The webhook URL is essential to Mollie because it forwards all payment changes that happen on Mollie to the integration and makes sure that Mollie and OroCommerce shop are in a consistent state. There is a detailed explanation on how to make your local server publicly visible using a tool called ngrok and set that public URL as a webhook URL in the Wiki pages (https://github.com/mollie/orocommerce/wiki/Testing-webhooks-during-development).

**Comment by clemzarch** [comment]
Understood, thanks.
